---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: install bind packages
  package:
    name: "{{ item }}"
    state: "{{ bind_packages_state }}"
  with_items: "{{ bind_packages | default(bind_packages_default) }}"

- name: configure daemon options
  lineinfile:
    regexp: '^OPTIONS='
    line: "OPTIONS=\"{{ bind_options }}\""
    dest: "{{ bind_conf_daemon_path | default(bind_conf_daemon_path_default) }}"
    insertafter: EOF
  when:
    - bind_conf_daemon_path != None
    - bind_conf_daemon_path != ''
    - bind_conf_daemon_path_default != None
    - bind_conf_daemon_path_default != ''
  notify: restart bind

- name: detect configuration permissions
  stat:
    path: "{{ bind_conf_global_path | default(bind_conf_global_path_default) }}"
  register: bind_permissions

- name: initialize configuration files
  copy:
    dest: "{{ item }}"
    content: ''
    force: no
    owner: "{{ bind_permissions.stat.pw_name }}"
    group: "{{ bind_permissions.stat.gr_name }}"
  with_items:
    - "{{ bind_conf_global_path | default(bind_conf_global_path_default) }}"
    - "{{ bind_conf_options_path | default(bind_conf_options_path_default) }}"
    - "{{ bind_conf_local_path | default(bind_conf_local_path) }}"

- name: manage global configuration file
  template:
    src: named.conf.j2
    dest: "{{ bind_conf_global_path | default(bind_conf_global_path_default) }}"
    owner: "{{ bind_permissions.stat.pw_name }}"
    group: "{{ bind_permissions.stat.gr_name }}"
  vars:
    conf: "{{ bind_conf_global | default(bind_conf_global_default) | named_conf }}"
  notify: restart bind

- name: manage options configuration file
  template:
    src: "{{ bind_conf_template }}"
    dest: "{{ bind_conf_options_path | default(bind_conf_options_path) }}"
    owner: "{{ bind_permissions.stat.pw_name }}"
    group: "{{ bind_permissions.stat.gr_name }}"
  vars:
    conf: "{{ bind_conf_options | default(bind_conf_options_default) | named_conf }}"
  notify: restart bind

- name: manage local configuration file
  template:
    src: named.conf.j2
    dest: "{{ bind_conf_local_path | default(bind_conf_local_path) }}"
    owner: "{{ bind_permissions.stat.pw_name }}"
    group: "{{ bind_permissions.stat.gr_name }}"
  vars:
    conf: "{{ bind_conf_local | named_conf }}"
  when:
    - bind_conf_local is defined
  notify: restart bind

- name: manage bind services
  service:
    name: "{{ bind_service_name | default(bind_service_name_default) }}"
    state: "{{ bind_service_status }}"
    enabled: "{{ bind_service_enabled }}"
