---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: Install bind packages
  package:
    name: "{{ item }}"
    state: "{{ bind_packages_state }}"
  become: "yes"
  with_items: "{{ bind_packages }}"

- name: configure daemon options
  lineinfile:
    regexp: '^OPTIONS='
    line: "OPTIONS=\"{{ bind_options }}\""
    dest: "{{ bind_conf_daemon_path }}"
    insertafter: EOF
  when:
    - bind_conf_daemon_path != None
    - bind_conf_daemon_path != ''
  notify: restart bind

- name: manage bind services
  become: yes
  ignore_errors: yes
  service:
    name: "{{ bind_service_name }}"
    state: "{{ bind_service_status }}"
    enabled: "{{ bind_service_enabled }}"
