---
- include: main.yml

- name: manage global configuration file
  template:
    src: named.conf.j2
    dest: "{{ bind_conf_global_path }}"
  vars:
    conf: "{{ bind_conf_global | named_conf }}"
  when:
    - bind_conf_global is defined
    - bind_conf_global != None
  notify: restart bind

- name: manage options configuration file
  template:
    src: named.conf.j2
    dest: "{{ bind_conf_options_path }}"
  vars:
    conf: "{{ bind_conf_options | named_conf }}"
  when:
    - bind_conf_options is defined
    - bind_conf_options != None
  notify: restart bind

- name: manage local configuration file
  template:
    src: named.conf.j2
    dest: "{{ bind_conf_local_path }}"
  vars:
    conf: "{{ bind_conf_local | named_conf }}"
  when:
    - bind_conf_local is defined
    - bind_conf_local != None
  notify: restart bind

#  - name: configure bind
#    template:
#      src: "{{ bind_conf_template }}"
#      dest: "{{ bind_conf_path }}"
#    become: no
#    when: bind_conf_path is defined
#    tags:
#      - "bind"
#    notify:
#      - restart bind
