---
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint .
driver:
  name: docker
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    privileged: yes
    command: /usr/sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: bionic
    image: geerlingguy/docker-ubuntu1804-ansible
    privileged: yes
    command: /sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_FILTER_PLUGINS: filter_plugins
verifier:
  name: testinfra
